"""adding value in item_custom_field_association association table

Revision ID: 04d73cfe1f79
Revises: 90e53f0ad183
Create Date: 2024-07-25 02:25:25.567441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04d73cfe1f79'
down_revision: Union[str, None] = '90e53f0ad183'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_custom_field_association', sa.Column('value', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item_custom_field_association', 'value')
    # ### end Alembic commands ###
