"""removing custom_field feature

Revision ID: 07fb17fc2b01
Revises: 04d73cfe1f79
Create Date: 2024-07-29 01:35:53.304870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '07fb17fc2b01'
down_revision: Union[str, None] = '04d73cfe1f79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_custom_field_association')
    op.drop_index('ix_custom_field_name', table_name='custom_field')
    op.drop_table('custom_field')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_field',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='custom_field_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_custom_field_name', 'custom_field', ['name'], unique=True)
    op.create_table('item_custom_field_association',
    sa.Column('item_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('custom_field_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('value', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['custom_field_id'], ['custom_field.id'], name='item_custom_field_association_custom_field_id_fkey'),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], name='item_custom_field_association_item_id_fkey'),
    sa.PrimaryKeyConstraint('item_id', 'custom_field_id', name='item_custom_field_association_pkey')
    )
    # ### end Alembic commands ###
