"""association tables

Revision ID: 90e53f0ad183
Revises: 3d3eb2ceba62
Create Date: 2024-07-25 02:05:10.571528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90e53f0ad183'
down_revision: Union[str, None] = '3d3eb2ceba62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_custom_field_association',
    sa.Column('item_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('custom_field_id', sa.UUID(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['custom_field_id'], ['custom_field.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.PrimaryKeyConstraint('item_id', 'custom_field_id')
    )
    op.create_table('item_tag_association',
    sa.Column('item_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('tag_id', sa.UUID(as_uuid=False), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['item.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('item_id', 'tag_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_tag_association')
    op.drop_table('item_custom_field_association')
    # ### end Alembic commands ###
